<a href="https://colab.research.google.com/github/sambit9238/Deep-Learning/blob/master/start_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
!pip3 install -U torch torchvision

Requirement already up-to-date: torch in /usr/local/lib/python3.6/dist-packages (1.6.0+cu101)
Requirement already up-to-date: torchvision in /usr/local/lib/python3.6/dist-packages (0.7.0+cu101)


In [4]:
import torch

In [7]:
x = torch.rand(5, 3)
print(x)

tensor([[0.1081, 0.8520, 0.4269],
        [0.9329, 0.3170, 0.1846],
        [0.2535, 0.5622, 0.6611],
        [0.5403, 0.3821, 0.1359],
        [0.4826, 0.6152, 0.9669]])


In [8]:
torch.empty(5, 3)

tensor([[5.9212e-36, 0.0000e+00, 2.1019e-44],
        [0.0000e+00, 1.4013e-45, 0.0000e+00],
        [1.2121e+04, 7.1846e+22, 9.2198e-39],
        [7.0374e+22, 5.0948e-14, 7.1846e+22],
        [9.2198e-39, 7.0374e+22, 5.0948e-14]])

In [9]:
torch.zeros(5, 3)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [10]:
x = torch.tensor([5.5, 3])
print(x)

tensor([5.5000, 3.0000])


In [11]:
#These methods will reuse properties of the input tensor, e.g. dtype, unless new values are provided by user

x = x.new_ones(5, 3, dtype=torch.double)      # new_* methods take in sizes
print(x)

x = torch.randn_like(x, dtype=torch.float)    # override dtype!
print(x)                                      # result has the same size

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 1.4040, -0.7761,  0.6523],
        [ 0.2967,  0.9208,  1.9486],
        [-0.6122, -0.0583, -0.6845],
        [ 1.0465,  1.7201,  1.4811],
        [-0.7210, -0.5113, -0.8721]])


In [12]:
x = torch.ones(5,3)
y = torch.ones(5,3)

In [13]:
%time x+y

CPU times: user 486 µs, sys: 112 µs, total: 598 µs
Wall time: 376 µs


tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])

In [14]:
%time torch.add(x, y)

CPU times: user 0 ns, sys: 232 µs, total: 232 µs
Wall time: 843 µs


tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])

In [15]:
#Addition: providing an output tensor as argument
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])


In [16]:
# adds x to y
y.add_(x)
print(y)
#Any operation that mutates a tensor in-place is post-fixed with an _. For example: x.copy_(y), x.t_(), will change x.

tensor([[2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.],
        [2., 2., 2.]])


In [17]:
x.numpy()

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [18]:
#Converting NumPy Array to Torch Tensor
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)
